//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompilationTechnologyExperiment {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompilationTechnologyExperiment.ErrorMessageResource", typeof(ErrorMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 文件内容为空，读取失败 的本地化字符串。
        /// </summary>
        internal static string FileEmptyError {
            get {
                return ResourceManager.GetString("FileEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在，读取失败 的本地化字符串。
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标识符以数字开头 的本地化字符串。
        /// </summary>
        internal static string IdStartWithNumber {
            get {
                return ResourceManager.GetString("IdStartWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实数的小数部分出现字母 的本地化字符串。
        /// </summary>
        internal static string NumberEFollowDot {
            get {
                return ResourceManager.GetString("NumberEFollowDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常数中有多个小数点 的本地化字符串。
        /// </summary>
        internal static string NumberMultiDotError {
            get {
                return ResourceManager.GetString("NumberMultiDotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常数中有多个指数字母e 的本地化字符串。
        /// </summary>
        internal static string NumberMultiE {
            get {
                return ResourceManager.GetString("NumberMultiE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型不存在 的本地化字符串。
        /// </summary>
        internal static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
    }
}
