//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompilationTechnologyExperiment {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class keyword {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal keyword() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompilationTechnologyExperiment.keyword", typeof(keyword).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 29 的本地化字符串。
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 26 的本地化字符串。
        /// </summary>
        public static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string BEGIN {
            get {
                return ResourceManager.GetString("BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 的本地化字符串。
        /// </summary>
        public static string BOOL {
            get {
                return ResourceManager.GetString("BOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        public static string CHAR {
            get {
                return ResourceManager.GetString("CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 25 的本地化字符串。
        /// </summary>
        public static string CONST {
            get {
                return ResourceManager.GetString("CONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 53 的本地化字符串。
        /// </summary>
        public static string DANYH {
            get {
                return ResourceManager.GetString("DANYH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 35 的本地化字符串。
        /// </summary>
        public static string DAYU {
            get {
                return ResourceManager.GetString("DAYU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 37 的本地化字符串。
        /// </summary>
        public static string DEQU {
            get {
                return ResourceManager.GetString("DEQU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 49 的本地化字符串。
        /// </summary>
        public static string DIAN {
            get {
                return ResourceManager.GetString("DIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 32 的本地化字符串。
        /// </summary>
        public static string DIV {
            get {
                return ResourceManager.GetString("DIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16 的本地化字符串。
        /// </summary>
        public static string DO {
            get {
                return ResourceManager.GetString("DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 51 的本地化字符串。
        /// </summary>
        public static string DOUHAO {
            get {
                return ResourceManager.GetString("DOUHAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 21 的本地化字符串。
        /// </summary>
        public static string ELSE {
            get {
                return ResourceManager.GetString("ELSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        public static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 33 的本地化字符串。
        /// </summary>
        public static string EQU {
            get {
                return ResourceManager.GetString("EQU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 23 的本地化字符串。
        /// </summary>
        public static string FALSE {
            get {
                return ResourceManager.GetString("FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13 的本地化字符串。
        /// </summary>
        public static string FOR {
            get {
                return ResourceManager.GetString("FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 39 的本地化字符串。
        /// </summary>
        public static string FUZHI {
            get {
                return ResourceManager.GetString("FUZHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 40 的本地化字符串。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 19 的本地化字符串。
        /// </summary>
        public static string IF {
            get {
                return ResourceManager.GetString("IF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8 的本地化字符串。
        /// </summary>
        public static string INPUT {
            get {
                return ResourceManager.GetString("INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        public static string INTEGER {
            get {
                return ResourceManager.GetString("INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 46 的本地化字符串。
        /// </summary>
        public static string LKUOHAO {
            get {
                return ResourceManager.GetString("LKUOHAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 48 的本地化字符串。
        /// </summary>
        public static string MAOHAO {
            get {
                return ResourceManager.GetString("MAOHAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 的本地化字符串。
        /// </summary>
        public static string MUL {
            get {
                return ResourceManager.GetString("MUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 28 的本地化字符串。
        /// </summary>
        public static string NOT {
            get {
                return ResourceManager.GetString("NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 27 的本地化字符串。
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9 的本地化字符串。
        /// </summary>
        public static string OUTPUT {
            get {
                return ResourceManager.GetString("OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10 的本地化字符串。
        /// </summary>
        public static string PROGRAM {
            get {
                return ResourceManager.GetString("PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11 的本地化字符串。
        /// </summary>
        public static string READ {
            get {
                return ResourceManager.GetString("READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 的本地化字符串。
        /// </summary>
        public static string REAL {
            get {
                return ResourceManager.GetString("REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 17 的本地化字符串。
        /// </summary>
        public static string REPEAT {
            get {
                return ResourceManager.GetString("REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 47 的本地化字符串。
        /// </summary>
        public static string RKUOHAO {
            get {
                return ResourceManager.GetString("RKUOHAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 50 的本地化字符串。
        /// </summary>
        public static string SEM {
            get {
                return ResourceManager.GetString("SEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 54 的本地化字符串。
        /// </summary>
        public static string SHUANGYH {
            get {
                return ResourceManager.GetString("SHUANGYH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7 的本地化字符串。
        /// </summary>
        public static string STRING {
            get {
                return ResourceManager.GetString("STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 的本地化字符串。
        /// </summary>
        public static string SUB {
            get {
                return ResourceManager.GetString("SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20 的本地化字符串。
        /// </summary>
        public static string THEN {
            get {
                return ResourceManager.GetString("THEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 14 的本地化字符串。
        /// </summary>
        public static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 22 的本地化字符串。
        /// </summary>
        public static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 38 的本地化字符串。
        /// </summary>
        public static string UNEQU {
            get {
                return ResourceManager.GetString("UNEQU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 18 的本地化字符串。
        /// </summary>
        public static string UNTIL {
            get {
                return ResourceManager.GetString("UNTIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24 的本地化字符串。
        /// </summary>
        public static string VAR {
            get {
                return ResourceManager.GetString("VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 15 的本地化字符串。
        /// </summary>
        public static string WHILE {
            get {
                return ResourceManager.GetString("WHILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 的本地化字符串。
        /// </summary>
        public static string WRITE {
            get {
                return ResourceManager.GetString("WRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 36 的本地化字符串。
        /// </summary>
        public static string XEQU {
            get {
                return ResourceManager.GetString("XEQU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 52 的本地化字符串。
        /// </summary>
        public static string XHX {
            get {
                return ResourceManager.GetString("XHX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 34 的本地化字符串。
        /// </summary>
        public static string XIAOYU {
            get {
                return ResourceManager.GetString("XIAOYU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 45 的本地化字符串。
        /// </summary>
        public static string 字符串型 {
            get {
                return ResourceManager.GetString("字符串型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 43 的本地化字符串。
        /// </summary>
        public static string 字符型 {
            get {
                return ResourceManager.GetString("字符型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 42 的本地化字符串。
        /// </summary>
        public static string 实型 {
            get {
                return ResourceManager.GetString("实型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 44 的本地化字符串。
        /// </summary>
        public static string 布尔型 {
            get {
                return ResourceManager.GetString("布尔型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 41 的本地化字符串。
        /// </summary>
        public static string 整型 {
            get {
                return ResourceManager.GetString("整型", resourceCulture);
            }
        }
    }
}
